spring:
  #Redis
  data:
    redis:
      host: localhost
      port: 6379
  #devtools
  devtools:
    restart:
      enabled: true
  #thymeleaf
  thymeleaf:
    cache: true
  #JDBC
  datasource:
    url: jdbc:mysql://localhost:3306/spring?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: springuser
    password: springuser
  #JPA
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update
logging:
  level:
    org:
      apache:
        coyote:
          http11: debug