spring:
  #Redis
  data:
    redis:
      host: localhost
      port: 6379
  #devtools
  devtools:
    restart:
      enabled: true
  #thymeleaf
  thymeleaf:
    cache: true
  #JDBC
  datasource:
    url: jdbc:mysql://localhost:3306/spring?serverTimezone=Asia/Seoul
    username: springuser
    password: springuser
  #JPA
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect